name: Run pipeline on GitLab

on: [push, pull_request]

jobs:
  gitlab:
    name: Run pipeline on GitLab
    runs-on: ubuntu-latest
    steps:
      - uses: Taucher2003/GitLab-Pipeline-Action@master
        with:
          GL_PROJECT_ID: 52107720
          GL_RUNNER_TOKEN: ${{ secrets.GITLAB_RUNNER_TOKEN }}
          GL_API_TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
          
